version: "3.7"

services:
  app:
    image: getting-started:latest
    build: ./app
    ports:
      - ${APP_PORT}:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - app-network

volumes:
  todo-mysql-data:

networks:
  app-network:
    driver: bridge